### ISSUE TITLE
Docker image is excessively large

### ISSUE THREAD

**Issue by gdevenyi** [volBrain/AssemblyNet#1]
Seems the Dockerfile for this tool is not public, nor is the code, but whatever process is being done to generate the image, it is (probably) not following best practices for docker:

![image](https://user-images.githubusercontent.com/3001850/177210273-729bb1b8-e99f-4724-a718-f12da6055017.png)

**Comment by volBrain** [comment]
Dear Gabriel, 
This docker contains the weights of 250 Unets (see paper). Moreover, we used Matlab MCR for preprocessing which is also heavy. Consequently, despite all the optimisations done following the best practice, the size is high. If our docker is too heavy for your application, you might find alternative from other teams. Best. Pierrick
