### ISSUE TITLE
Ranges with Scores

### ISSUE THREAD

**Issue by rogiedodgie** [volBrain/AssemblyNet#3]
Is there a way to get the normative range for a person (shown in the PDF) as well as the actual volume values in the .csv file output? 
This would be useful for identifying frequencies of people showing abnormally high or low volumes for their age/sex.

**Comment by pierrickvolbrain** [comment]
Dear Roger,
Currently this information is not included into the .csv in order to keep its size as small as possible.
Only the .pdf contains these normative bounds.
If many of you ask for it, we will think about including it in the next version of AssemblyNet. 
Best,
Pierrick

**Comment by rogiedodgie** [comment]
I do think that the unique aspect of volBrain is that it gives you this normative data. 
Without it, it is hard to justify how it would be better than other tools, like Cat12 for example, unless I am missing something. 
While volBrain does do this faster than other tools, I do think that including these data in the output would be very helpful to researchers looking to compare their unique populations to the general population (i.e. more pubs would come from this).

**Comment by BorisMansencal** [comment]
We have added the normative ranges of normalized volumes used in AssemblyNet (in the report when age is provided) through the following files: female_ranges.csv, male_ranges.csv, and general_range.csv.
There is also a new section in the README about that.

**Comment by rogiedodgie** [comment]
Thank you Boris,
I will tell my colleagues!
This is great news and I hope that this will increase usage of your
outstanding tool.
Best,
Roger
