### ISSUE TITLE
-age-sex-csv

### ISSUE THREAD

**Issue by Luoyu-Wang** [volBrain/AssemblyNet#4]
Our use of the parameter -age-sex-csv has been always failing and I don‘t know if there is something wrong with the csv file：
/T1/S0004.nii,66,Male
/T1/S0005.nii,58,Female
/T1/S0006.nii,69,Female
/T1/S0007.nii,75,Female
/T1/S0010.nii,69,Female
/T1/S0012.nii,64,Male
/T1/S0016.nii,79,Female
/T1/S0017.nii,60,Female

**Comment by BorisMansencal** [comment]
Could you try without the leading "/" in the paths ?
```
T1/S0004.nii,66,Male
T1/S0005.nii,58,Female
T1/S0006.nii,69,Female
T1/S0007.nii,75,Female
T1/S0010.nii,69,Female
T1/S0012.nii,64,Male
T1/S0016.nii,79,Female
T1/S0017.nii,60,Female
```

**Comment by Luoyu-Wang** [comment]
Thank you for your reply but I found that there are still errors:
cmd= python3 -u make_reports.py -root-dir /data -global-csv /out/global_volumetry_info.csv -age-sex-csv /out/agesex1.csv "/tmp/t1_0.nii.gz" "/data/S0004.nii"
python3 -u make_reports.py -root-dir /data -global-csv /out/global_volumetry_info.csv -age-sex-csv /out/agesex1.csv "/tmp/t1_0.nii.gz" "/data/S0004.nii"
ERROR: column filename not found in filename: /out/agesex1.csv
age=UNKNOWN sex=UNKNOWN

**Comment by BorisMansencal** [comment]
Yes, I forgot to say that the first row of the csv must have the columns names.
(I will update the README accordingly)
For example:
```
#filename,age,sex
T1/S0004.nii,66,Male
T1/S0005.nii,58,Female
T1/S0006.nii,69,Female
T1/S0007.nii,75,Female
T1/S0010.nii,69,Female
T1/S0012.nii,64,Male
T1/S0016.nii,79,Female
T1/S0017.nii,60,Female
```

If it still does not work, could you tell what your exact command line is ?
( If you call the docker with "-v /some_path/T1:/data", you do not have to put "T1/" in the filenames in the csv. 
  If you have "T1/" in the filenames in the csv, it means that "T1" is a subdirectory of the directory mounted as /data, and that you are using "-recursive" on the command line)

**Comment by Luoyu-Wang** [comment]
Thank you and the issue has been solved.
