### ISSUE TITLE
problems for docker in ubuntu 20.04 on windows

### ISSUE THREAD

**Issue by liangpeng0222** [volBrain/AssemblyNet#6]
Dear professor,

Thanks for your amazing tutorial! I was stuck in the following problems.

First, I've Install Windows Subsystem for Linux (WSL) 2 and also download the docker-desktop

Also, I've entered the command line ( sudo docker pull volbrain/assemblynet:1.0.0 ) in Ubuntu 20.04 on windows.

But, the problems I encountered is that I was confused about the command line (sudo docker run --rm -v /absolute/path/to/images:/data volbrain/assemblynet:1.0.0 /data/image.nii). What is the absolute path meaning?

If I have the nii file located in the path of my notebook such that "C:\Users\Downloads\mybrainimg.nii". What should I input my command line to get the AssemblyNet results. Thank you!

Sincerely,
Lonnie

**Comment by BorisMansencal** [comment]
In the WSL/Ubuntu terminal, the windows filesystem is available in /mnt. For example, "C:`\Users\Downloads\mybrainimg.nii" will be available as "/mnt/c/Users/Downloads/mybrainimg.nii". So you should be able to run assemblynet (on the CPU) with the command:
sudo docker run --rm -v /mnt/c/Users/Downloads:/data volbrain/assemblynet:1.0.0 /data/mybrainimg.nii 
(I you followed the instructions and added your user to the docker group, you don't need the "sudo")

See https://github.com/volBrain/AssemblyNet/blob/main/README.md#how-to-use-assemblynet for more information on the command line options of AssemblyNet.
See https://learn.microsoft.com/en-us/windows/wsl/filesystems for more information on WSL filesystems.

**Comment by liangpeng0222** [comment]
<img width="737" alt="image" src="https://user-images.githubusercontent.com/111492052/216773330-470f04d8-ce6b-46a6-9c6b-533c0f00de38.png">

Dear professor,
Thanks for your reply! I could run the command line ! 

However, there are still some problems with the picture above. 
Also, after I run the command: sudo docker run --rm -v /mnt/c/Users/Downloads:/data volbrain/assemblynet:1.0.0 /data/mybrainimg.nii, where can I find the files such as native_mask_filename.nii.gz in my system and how to extract these files? Thank you

Best regards, 
Lonnie

**Comment by BorisMansencal** [comment]
You were able to run the command, but the process crashed.
It seems to be in the segmentation (at 1mm).
Is it the end of the message that you get in the terminal? It just says that it was killed by the SIGKILL signal but not much more...
Could you try on the image that we provide https://github.com/volBrain/AssemblyNet/blob/main/example/mni_t1_my_brain.nii.gz to check if you have the same problem?
Could you also tell us more about the configuration of the machine where you run the software (CPU, memory, ...)?

When the process runs correctly, and as you did not specify an output directory in your command, the produced files should be in the same directory that the input image at the end.

**Comment by liangpeng0222** [comment]
Dear professor, 
Thanks for your patience! When I use the example image also get the same errors above the picture previously

In the middle of my execution:

<img width="699" alt="image" src="https://user-images.githubusercontent.com/111492052/216811808-057029ba-fd8e-4afc-9375-80d2b123e73c.png">

Is this warning valid to get the result?

Also, the configuration of my notebook is below.

<img width="946" alt="image" src="https://user-images.githubusercontent.com/111492052/216811955-b38c4432-0347-4f48-9a62-c91a55dda030.png">

On the other hand, I also give my CPU information.

<img width="948" alt="image" src="https://user-images.githubusercontent.com/111492052/216812021-88384f28-b07a-4e75-b777-2683db126740.png">

Even more the memory information.

<img width="479" alt="image" src="https://user-images.githubusercontent.com/111492052/216812070-3930a57c-0187-438c-bb87-dd741ab0c07c.png">

The reason why I can't get the result is I think that the memory is not  sufficient to execute it. That is just my guess!

Sincerely,
Lonnie

**Comment by BorisMansencal** [comment]
Exactly. You do not have enough memory.
We recommend at least 6GB (See the prerequisistes https://github.com/volBrain/AssemblyNet#prerequisites ).

**Comment by liangpeng0222** [comment]
Dear professor,

Thanks for your helping. I've solved the problem.

Best regards,
Lonnie
