### ISSUE TITLE
Atlas for Visualization of results

### ISSUE THREAD

**Issue by rnorlund** [volBrain/AssemblyNet#7]
After using volBrain to generate results, i would like to display areas for a single subject that were higher than average for GMV.
Which 3D Brain Atlas should I download for visualization purposes (i.e. what is the name of the atlas used by volBrain, and where can I download it from).
Roger

**Comment by volBrain** [comment]
Volbrain works at mni space so the mni152 atlas will work JoseEnviado desde mi teléfono Huawei-------- Mensaje original --------Asunto: [volBrain/AssemblyNet] Atlas for Visualization of results (Issue #7)De: rnorlund Para: volBrain/AssemblyNet CC: Subscribed 
After using volBrain to generate results, i would like to display areas for a single subject that were higher than average for GMV.
Which 3D Brain Atlas should I download for visualization purposes (i.e. what is the name of the atlas used by volBrain, and where can I download it from).
Roger

**Comment by rnorlund** [comment]
Hi Jose,
The MNI image is actually a brain template (average brain).
I am referring to visualization of the individual ROIs that make up the brain, which is referred to as an atlas file (usually a 3D nii file with integers for each region).
Roger

**Comment by volBrain** [comment]
We Dont have that you have your segmentation for each case 

Jose

Enviado desde mi iPad

**Comment by volBrain** [comment]
In my papers, I usually create an adapted template using our own script or ANTstemplateconstruction and then I apply the estimated deformation fields to the segmentations obtain on my population before averaging them. Therefore, I obtain an Atlas with the corresponding parcelation. 

Pierrick.
